create database DEPTEMP 
USE DEPTEMP
CREATE TABLE DEPARTMENT
(
	DEPARTMENTNO INTEGER PRIMARY KEY,
	DEPARTMENTNAME CHAR(25) NOT NULL,
	LOCATION CHAR(25) NOT NULL
)
CREATE TABLE EMPLOYEE
(
	EMPNO INT PRIMARY KEY,
	FNAME VARCHAR(15) NOT NULL,
	LNAME VARCHAR(15) NOT NULL,
	JOB VARCHAR(25) NOT NULL,
	HIREDATE DATETIME NOT NULL,
	SALARY NUMERIC NOT NULL,
	COMMISION NUMERIC,
	DEPARTMENTNO INT,
	CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY (DEPARTMENTNO) REFERENCES DEPARTMENT(DEPARTMENTNO)
)
INSERT INTO DEPARTMENT VALUES(10,N'ACCOUNTING',N'MELBOURNE')
UPDATE DEPARTMENT SET DEPARTMENTNAME=N'RESEARCH'  WHERE DEPARTMENTNO=20
INSERT INTO DEPARTMENT VALUES(20,N'REARCH',N'ADEALIDE')
DELETE  FROM DEPARTMENT WHERE DEPARTMENTNO=20
INSERT INTO DEPARTMENT VALUES(30,N'SALES',N'SYDNEY')
INSERT INTO DEPARTMENT VALUES(40,N'OPERATIONS',N'PERTH')

INSERT INTO EMPLOYEE(EMPNO,FNAME,LNAME,JOB,HIREDATE, SALARY,DEPARTMENTNO) VALUES(1,N'JOHN',N'SMITH',N'CLERK','17-Dec-1980',800,20)
 
 INSERT INTO EMPLOYEE(EMPNO,FNAME,LNAME,JOB,HIREDATE, SALARY,COMMISION,DEPARTMENTNO) VALUES(2,N'PERTER',N'ALLEN',N'SALESMAN','20-FEB-1981',1600,300,30)
DELETE  FROM EMPLOYEE WHERE EMPNO=2
INSERT INTO EMPLOYEE VALUES(3,N'KATE',N'WARD',N'SALESMAN','22-FEB-1981',1250,500,30)
INSERT INTO EMPLOYEE(EMPNO,FNAME,LNAME,JOB,HIREDATE, SALARY,DEPARTMENTNO) VALUES(4,N'JACK',N'JONES',N'MANAGER','02-APR-1981',2975,20)
INSERT INTO EMPLOYEE VALUES(5,N'JOE',N'MARTIN',N'SALESMAN','28-SEP-1981',1250,1400,30)

SELECT * FROM DEPARTMENT
SELECT * FROM EMPLOYEE
--CAU 3
SELECT EMPNO, FNAME, LNAME
FROM EMPLOYEE
WHERE FNAME='KATE'
--CAU 4
SELECT FNAME+ '    ' +LNAME AS 'FULLNAME', SALARY,SALARY*0.1 AS 'TANG LUONG'
FROM EMPLOYEE
--CAU 5
SELECT FNAME, LNAME, HIREDATE 
FROM EMPLOYEE
WHERE YEAR(HIREDATE) = '1981'
ORDER BY LNAME ASC
--CAU 6
SELECT AVG(SALARY)AS 'LUONG TB', MAX(SALARY) AS 'LUONG CAO NHAT', MIN(SALARY) AS 'LUONG THAP NHAT'
FROM EMPLOYEE
GROUP BY DEPARTMENTNO
--CAU 7
SELECT DEPARTMENTNO, COUNT(*) AS 'SO NGUOI'
FROM EMPLOYEE
GROUP BY DEPARTMENTNO
--CAU 8
SELECT DEPARTMENT.DEPARTMENTNO, DEPARTMENTNAME,FNAME+'  '+LNAME AS FULLNAME,JOB,SALARY
FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENTNO = EMPLOYEE.DEPARTMENTNO
--CAU 9
SELECT COUNT(*) AS 'TONGNGUOI', EMPLOYEE.DEPARTMENTNO 
FROM EMPLOYEE
GROUP BY EMPLOYEE.DEPARTMENTNO
SELECT DEPARTMENT.DEPARTMENTNO, DEPARTMENT.DEPARTMENTNAME,DEPARTMENT.LOCATION,SONGUOI.TONGNGUOI

FROM DEPARTMENT INNER JOIN SONGUOI ON DEPARTMENT.DEPARTMENTNO=SONGUOI.DEPARTMENT